### **Code : 미생물 본설문 - CARD 전처리**
##### Writer : Donghyeon Kim
##### Update : 2024.11.23.

---

#### **0. Prior Settings**

In [1]:
# 1. Library
from pathlib import Path
import os
import pandas as pd
import numpy as np
import openpyxl

##### Data : 미생물 예비설문 응답

In [3]:
# Windows : Directory '\\'
# Mac : Directory '/'

# Data가 존재하는 폴더
folder_root = 'C:/Users/mazy4/Dropbox/6. C&S Lab/7. 2024 Project/4. 야생생물 경제가치_생물자원관/2. 분석/3. SPSS Code/2. 본설문_SPSS/1. 미생물'

# csv file
csv_name = folder_root + '/' + '0_미생물_CARDREP173.csv'

# Data 호출
file_data_raw = pd.read_csv(csv_name)

In [4]:
file_data_raw

,REP,CARD1,CARD2,CARD3,CARD4,CARD5,CARD6,CARD7,CARD8,CARD9,...,CARD13,CARD14,CARD15,CARD16,CARD17,CARD18,CARD19,CARD20,CARD21,CARD22
0,1,7,10,2,6,2,2,1,5,7,...,3,4,6,8,6,7,3,4,5,3
1,2,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
2,3,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,4,11,9,1,1,6,9,8,9,1,...,3,4,6,1,5,7,7,7,6,7
4,5,7,8,5,5,7,7,5,5,6,...,7,7,5,5,5,6,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,169,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
169,170,6,6,6,6,7,6,6,7,6,...,6,6,7,6,7,7,7,7,6,6
170,171,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
171,172,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
172,173,6,6,5,5,5,6,5,6,6,...,6,5,6,5,5,6,6,5,5,6

---

#### **1. CARD 값 1씩 모두 빼기**

In [5]:
# 모든 CARD에 대해서 1씩 빼기
for i in range(1, 23):
    column_name = f'CARD{i}'
    if column_name in file_data_raw.columns:
        file_data_raw[column_name] = file_data_raw[column_name] - 1

In [6]:
file_data_raw

,REP,CARD1,CARD2,CARD3,CARD4,CARD5,CARD6,CARD7,CARD8,CARD9,...,CARD13,CARD14,CARD15,CARD16,CARD17,CARD18,CARD19,CARD20,CARD21,CARD22
0,1,6,9,1,5,1,1,0,4,6,...,2,3,5,7,5,6,2,3,4,2
1,2,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,10,8,0,0,5,8,7,8,0,...,2,3,5,0,4,6,6,6,5,6
4,5,6,7,4,4,6,6,4,4,5,...,6,6,4,4,4,5,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,169,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
169,170,5,5,5,5,6,5,5,6,5,...,5,5,6,5,6,6,6,6,5,5
170,171,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
171,172,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
172,173,5,5,4,4,4,5,4,5,5,...,5,4,5,4,4,5,5,4,4,5

---

#### **2. csv file 저장**

In [7]:
# 저장 경로
output_path = folder_root + '/' + '1_미생물_CARDREP173.csv'

# csv file
file_data_raw.to_csv(output_path, index=False)