### **Code : 천연물 본설문 - CARD 전처리**
##### Writer : Donghyeon Kim
##### Update : 2024.11.23.

---

#### **0. Prior Settings**

In [1]:
# 1. Library
from pathlib import Path
import os
import pandas as pd
import numpy as np
import openpyxl

##### Data : 천연물 예비설문 응답

In [2]:
# Windows : Directory '\\'
# Mac : Directory '/'

# Data가 존재하는 폴더
folder_root = 'C:/Users/mazy4/Dropbox/6. C&S Lab/7. 2024 Project/4. 야생생물 경제가치_생물자원관/2. 분석/3. SPSS Code/2. 본설문_SPSS/2. 천연물'

# csv file
csv_name = folder_root + '/' + '0_천연물_CARDREP123.csv'

# Data 호출
file_data_raw = pd.read_csv(csv_name)

In [3]:
file_data_raw

,REP,CARD1,CARD2,CARD3,CARD4,CARD5,CARD6,CARD7,CARD8,CARD9,...,CARD13,CARD14,CARD15,CARD16,CARD17,CARD18,CARD19,CARD20,CARD21,CARD22
0,13,2,3,9,2,3,3,9,5,9,...,2,4,4,7,3,5,3,4,9,9
1,14,3,4,6,2,5,3,7,4,7,...,2,2,5,3,3,3,3,3,3,6
2,15,7,7,7,9,8,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
3,16,9,9,11,9,8,8,8,8,11,...,6,10,9,7,9,10,10,10,11,11
4,17,5,6,11,6,9,9,11,11,11,...,6,6,5,5,7,7,7,8,8,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,131,6,6,8,6,8,7,7,7,7,...,7,7,7,7,7,7,7,7,6,7
119,132,1,4,8,1,1,1,1,3,3,...,1,3,1,1,1,4,4,4,1,6
120,133,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
121,134,1,1,8,8,1,1,1,1,1,...,1,1,1,1,3,1,3,1,1,5
122,135,5,6,5,6,5,6,5,6,5,...,6,5,6,5,6,5,6,5,6,5

---

#### **1. CARD 값 1씩 모두 빼기**

In [4]:
# 모든 CARD에 대해서 1씩 빼기
for i in range(1, 23):
    column_name = f'CARD{i}'
    if column_name in file_data_raw.columns:
        file_data_raw[column_name] = file_data_raw[column_name] - 1

In [5]:
file_data_raw

,REP,CARD1,CARD2,CARD3,CARD4,CARD5,CARD6,CARD7,CARD8,CARD9,...,CARD13,CARD14,CARD15,CARD16,CARD17,CARD18,CARD19,CARD20,CARD21,CARD22
0,13,1,2,8,1,2,2,8,4,8,...,1,3,3,6,2,4,2,3,8,8
1,14,2,3,5,1,4,2,6,3,6,...,1,1,4,2,2,2,2,2,2,5
2,15,6,6,6,8,7,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
3,16,8,8,10,8,7,7,7,7,10,...,5,9,8,6,8,9,9,9,10,10
4,17,4,5,10,5,8,8,10,10,10,...,5,5,4,4,6,6,6,7,7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,131,5,5,7,5,7,6,6,6,6,...,6,6,6,6,6,6,6,6,5,6
119,132,0,3,7,0,0,0,0,2,2,...,0,2,0,0,0,3,3,3,0,5
120,133,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
121,134,0,0,7,7,0,0,0,0,0,...,0,0,0,0,2,0,2,0,0,4
122,135,4,5,4,5,4,5,4,5,4,...,5,4,5,4,5,4,5,4,5,4

---

#### **2. csv file 저장**

In [6]:
# 저장 경로
output_path = folder_root + '/' + '1_천연물_CARDREP123.csv'

# csv file
file_data_raw.to_csv(output_path, index=False)